README.md
resample/bootstrap.py
resample/tests/test_bootstrap.py

Closes https://github.com/dsaxton/resample/issues/7
cc @HDembinski

Remove smoothing option

---

requirements.txt
setup.py
src/resample/bootstrap.py
src/resample/tests/test_bootstrap.py

* compute jackknife with numba
* fixes jackknife_bias formula
* adds jackknife_bias_corrected
* possibly faster and more accurate jackknife_variance
* added unit tests for jackknife functions
* added docu

jackknife additions and fixes, numba acceleration

---

src/resample/bootstrap.py

Small docstring edits for consistency / aesthetics

Update jackknife docstrings

---

resample/bootstrap.py

Rename kwds -> kwargs

---

resample/bootstrap.py

Closes https://github.com/dsaxton/resample/issues/35
As mentioned there's no reason why the variance can't be allowed to be less than one. Also renamed fit_kwds to fit_kwargs.

Don't fix fscale for t distribution

---

doc/conf.py

fixes RTD build

---

resample/tests/test_bootstrap.py

uses constants everywhere and fixes test_bias_on_unbiased

---

notebooks/confidence_intervals.ipynb
resample/bootstrap.py
resample/jackknife.py
resample/tests/test_bootstrap.py

Closes https://github.com/dsaxton/resample/issues/60

Replace "replica" -> "replicate"

---

resample/bootstrap.py

Clean string formatting

---

doc/changelog.rst
resample/version.py

@HDembinski I'm going to go ahead and push these changes through since the PyPI distribution is partially broken

Bump version to 1.0.1

---

.github/workflows/check-style-and-types.yml
.github/workflows/run-tests.yml

I think the current configuration is causing certain events to trigger duplicate CI jobs, maybe this fixes it

Fix duplicate CI runs

---

.readthedocs.yaml
doc/requirements.txt

fix RTD build latest

---

src/resample/_util.py
src/resample/bootstrap.py
src/resample/permutation.py
tests/test_bootstrap.py

implement extended bootstrap

---

benchmarks/test_rcont.py
benchmarks/test_usp.py
doc/bench_rcont.json
doc/plot_bench.py
src/resample/_util.py
src/resample/permutation.py
tests/test_permutation.py
tests/test_util.py

Closes #141 
A test was added to see which calculation of the p-value is correct. It looks like the naive calculation is correct.

Add check of pvalue

---

.github/workflows/test.yml
setup.cfg
src/resample/bootstrap.py
src/resample/jackknife.py

Added examples to functions in `resample.bootstrap` and `resample.jackknife`.
Improved documentation of functions in `resample.bootstrap`.

add examples and test them

---

.gitignore
pyproject.toml
setup.cfg
src/resample/bootstrap.py
tests/test_bootstrap.py

fix extended when samples are multi-dimensional

---

.github/workflows/test.yml

ci: there’s an official coverage action

---

.github/workflows/test.yml

Everything was running on Ubuntu.

ci: fix OS

---

pyproject.toml

There seems to be a 3.12 test.

chore: 3.12 classifier

---

.pre-commit-config.yaml
pyproject.toml
src/resample/_util.py

chore: modernize ruff settings
