scikit-hep/resample

resample/__init__.py
This allows one to write
```
import resample
resample.jackknife.resample(...)
```
Without this, one can only do
```
from resample import jackknife
jackknife.resample(...)
```
I think it is common style to allow both uses, see e.g. numpy.
=> import submodules in `__init__.py`

benchmarks/test_bootstrap.py
I think this is a typo in the bootstrap benchmarks
=> Fix run_resample in bootstrap benchmarks

resample/bootstrap.py, resample/tests/test_bootstrap.py, setup.py
I added a warning to the bias computation with the bootstrap. Wording should be further improved for clarity.
I discovered that the bootstrap cannot detect biases of the kind (unbiased estimate + constant / N), where N is the number of observations, which the jackknife does detect and remove exactly. @dsaxton You can see it for yourself if you apply the bootstrap bias computation on the test function `def bad_mean(x): return (np.sum(x) + 2) / len(x)` that I used to test the jackknife. The bootstrap bias considers this function unbiased.
Somehow the meaning of the two bias computations is different. The jackknife computes the bias of the estimator on the finite sample with respect to the asymptotic limit. The bootstrap bias seems to compute something different.
=> add bias, bias_corrected, and variance to bootstrap module

resample/__init__.py, resample/bootstrap.py, resample/empirical.py, resample/jackknife.py, resample/permutation.py, resample/tests/test_bootstrap.py, resample/tests/test_empirical.py, resample/tests/test_jackknife.py
Closes https://github.com/dsaxton/resample/issues/31
While I don't think these names are great necessarily they're better than the `_fn` suffixes being used currently (I think `quantile_function_gen` is a slight improvement over `quantile_gen` since it makes it clear it's the quantile function that's being returned).
Also doing some other small cleaning (i.e., import sorting, removing what seem to be unnecessary underscore prefixes in imports; the functions aren't internal to the module and if they were I'd think the underscore should be part of the name). I'm actually surprised the CI wasn't failing due to formatting issues.
=> Rename higher-order functions

resample/bootstrap.py
~Pretty straightforward fix here. Minor nitpicky detail: I'm calling the bootstrap samples _replicates_ however I noticed you call them _replicas_. In my experience the former is more common, but in any event I think it'd be good the use the same term consistently in the documentation so maybe we pick one.~
Closes https://github.com/dsaxton/resample/issues/51
=> Change default size for bootstrap.resample

resample/bootstrap.py
Some docstring cleanup: ~ci_method isn't optional and default is "bca"~, also some small spelling / stylistic changes. In addition I added a note about possible failure of the bootstrap, but feel free to suggest changes.
Edit: Noticed the docstring for bootstrap.resample is not right either so doing more general clean up.
=> Clean bootstrap.resample docstrings

resample/bootstrap.py, resample/empirical.py, resample/jackknife.py, resample/permutation.py
Fixing some numpydoc errors (e.g., Notes should go after Yields / Returns). I think adding numpydoc validation to CI could also be good.
Edit: while updating noticed that permutation.py is still using np.random.seed so switched over to using the rng instead.
=> Fix numpydoc errors

resample/bootstrap.py, resample/tests/test_bootstrap.py
Closes #85 and #84 
There is no proper way to fix #84, but returning an empty interval makes more sense than returning (nan, nan).
=> fixing issues and add test

resample/bootstrap.py, resample/jackknife.py, tests/test_bootstrap.py, tests/test_jackknife.py
Closes #112 
This allows 
```py
for ai, bi, ... in resample(a, b, ...):
pass
```
under the condition that `a`, `b`, ... have the same lengths. The arguments are resampled in such a way that the relative pairings remain intact, e.g. the pair `a[1], b[1]` may be duplicated by the resampling at `a[5], b[5]`.
Code with positional arguments like `resample(a, 10)` for `resample(a, size=10)` is still working, but generates a `VisibleDeprecationWarning`.
=> Resample several arguments

resample/bootstrap.py, resample/jackknife.py, tests/test_bootstrap.py
We want to support extra args in most other functions as well, not only in `resample`. This is implemented here.
=> Support several args in additional bootstrap functions

src/resample/permutation.py, tests/test_permutation.py
Compute a Wilson score interval for the p-value (cheap) and return this as part of the `TestResult`.
This helps to gauge how statistically accurate the computed p-value is or whether the test has to be run with more permutations.
=> implement uncertainty of pvalue

.pre-commit-config.yaml, src/resample/__init__.py, src/resample/bootstrap.py, src/resample/empirical.py, src/resample/jackknife.py, src/resample/permutation.py, tests/test_permutation.py
Rename pearson, spearman to pearsonr, spearmanr to be consistent with scipy.
=> renaming pearson, spearman

src/resample/permutation.py, tests/test_permutation.py
This removes the KS test, since the SciPy version is exact for small samples and uses the asymptotic formula only for very large samples when it is really applicable. The SciPy test is also orders of magnitude faster.
=> remove ks test

src/resample/permutation.py, tests/test_permutation.py
This removes the mannwhitneyu test, since the scipy version is exact for small samples so we cannot offer any advantage.
=> remove mannwhitneyu

.github/workflows/coverage.yml, .gitignore, benchmarks/test_usp.py, setup.cfg, src/resample/permutation.py, tests/test_permutation.py
Richard Samworth pointed out in a comment by email, that an iterative algorithm which computes the number permutation samples dynamically makes the number of permutations used by the test a function of the resampled data set, but it has to be independent of that set if the Type I error probabilities should hold theoretically.
One possibility was to use the worst case value 0.5 and compute the number of required samples from that, but this is very pessimistic when the pvalue is very small (orders of magnitude). As a compromise, this patch uses only two iterations. In the first iteration, a burn sample of 10 permutations is used to get a crude estimate of the pvalue. The required number of samples is then computed from the pvalue obtained in the burn sample. The second sample is …
=> Fix dynamic calculation of required test samples

pyproject.toml
As Henry explained, this is no longer needed.
=> remove wheel, not needed

src/resample/permutation.py, tests/test_permutation.py
After discussion with Richard Samworth, it seems silly to add a Wilson interval for the p-value obtained from a permutation test. Instead we follow their approach and compute the p-value in such a way that it is guaranteed to be an upper limit for the actual Type I error of the test.
=> remove intervals from test result and calculate pvalue conservatively

.github/workflows/coverage.yml, .github/workflows/test.yml, pyproject.toml, setup.cfg, src/rcont.c, src/resample/_ext.c
We pin the numpy version during build to the oldest version supported by that version of python, to avoid using a newer Numpy C-API during the build than what is available at runtime.
=> attempt to fix build

src/resample/_deprecated.py, src/resample/bootstrap.py, tests/test_bootstrap.py
`bootstrap.bias` and `bootstrap.bias_corrected` are deprecated.
The bias estimation with the bootstrap seem to work in our tests, but it is not something that people in the field do, and there is no proof that this is the proper way.
To be on the safe side, we should not offer this. People should use the jacknife for bias correction.
=> Remove bias estimation from bootstrap module

src/resample/bootstrap.py, tests/test_bootstrap.py
Adds `bootstrap.covariance` in addition to `bootstrap.variance`. The former computes the full covariance matrix if the function returns a vector, while the latter computes the variance element-wise.
The docstring of `bootstrap.variance` was clarified with respect to this point.
=> add covariance

pyproject.toml, src/resample/bootstrap.py, src/resample/jackknife.py, src/resample/permutation.py, tests/test_bootstrap.py, tests/test_jackknife.py, tests/test_permutation.py
Replace all numpy.VisibleDeprecationWarning by FutureWarning, which is more appropriate.
=> use FutureWarning instead of VisibleDeprecationWarning

pyproject.toml, src/resample/bootstrap.py, src/resample/jackknife.py, src/resample/permutation.py, tests/test_bootstrap.py, tests/test_jackknife.py, tests/test_permutation.py
The VisibileDeprecationWarning from numpy is replaced with the builtin FutureWarning.
=> Replace deprecation warnings

tests/test_bootstrap.py
DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
The only way to support old versions of NumPy is to pass positionally.
=> tests: newshape deprecated in favor of shape
